### PR TITLE
Test/mysql binds

### PR DESCRIPTION
**Pull request by weiznich**
I want to check some assumptions how binds work with libmysqlclient and mysql/maria db in general. As I do not have the capacity to do extensive testing on different versions out there I hope that the diesel community can help with this. If you want to help please checkout this branch and execute the following command inside the `diesel` folder (so `diesel/diesel` if you from the directory where you cloned the branch)
```shell
DATABASE_URL=mysql://your/db/url TEST_THREADS=1 cargo test --features "mysql extras" check_
```

If one on the tests fail it would be great to get the error message (+ backtrace) as comment here. Additionally trying to modify the tests (in ` diesel/src/mysql/connection/bind.rs`) in such a way that they pass for your db version would also helpful.

For anyone with an deeper knowledge of the mysql wire protocol: Feel free to add comments on the actual changes and interpretations I've made.

### CODE REVIEW

**Comment by weiznich** [comment]
Pinging @p-alik, because they've done some great mysql work regarding to diesel in the last time.

**Comment by p-alik** [comment]
* `check_all_the_types` 
```diff
diff --git a/diesel/src/mysql/connection/bind.rs b/diesel/src/mysql/connection/bind.rs
index 2a2b9704..cc5aa73f 100644
--- a/diesel/src/mysql/connection/bind.rs
+++ b/diesel/src/mysql/connection/bind.rs
@@ -800,7 +800,7 @@ mod tests {
         assert!(!multipoint_col.flags.contains(Flags::BINARY_FLAG));
         assert_eq!(
             to_value::<Text, String>(multipoint_col).unwrap(),
-            "MULTIPOINT(0 0,10 10,10 20,20 20)"
+            "MULTIPOINT((0 0),(10 10),(10 20),(20 20))"
         );
 
         let multilinestring_col = &results[30].0;
@@ -846,7 +846,7 @@ mod tests {
         );
 
         let json_col = &results[33].0;
-        assert_eq!(json_col.tpe, ffi::enum_field_types::MYSQL_TYPE_BLOB);
+        assert_eq!(json_col.tpe, ffi::enum_field_types::MYSQL_TYPE_JSON);
         assert!(!json_col.flags.contains(Flags::NUM_FLAG));
         assert!(json_col.flags.contains(Flags::BLOB_FLAG));
         assert!(!json_col.flags.contains(Flags::SET_FLAG));
```
* `check_enum_bind` and `check_set_bind` failed 
```
thread 'mysql::connection::bind::tests::check_set_bind' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "Using unsupported buffer type: 254  (parameter: 1)")', src/libcore/result.rs:1165:5
```
* `check_json_bind` failed on
https://github.com/weiznich/diesel/blob/ea29a9ee4572aab54b3710e60fd6c01fafe0b46a/diesel/src/mysql/connection/bind.rs#L1029-L1037

Tested only on `mysqld  Ver 10.3.15-MariaDB for Linux on x86_64 (MariaDB Server)` yet.
See [cargo output](https://pastebin.com/SXFHYxV5)

**Comment by weiznich** [comment]
That's interesting as I'm getting different results (without any changes to the code):

```
running 4 tests
test mysql::connection::bind::tests::check_all_the_types ... ok
test mysql::connection::bind::tests::check_enum_bind ... FAILED
test mysql::connection::bind::tests::check_set_bind ... FAILED
test mysql::connection::bind::tests::check_json_bind ... ok
```
(Enum and set tests fail with similar error messages, seems like those variants are just not supported in `libmysqlclient` 🤔 )

## Version information:

```
mysql --version                                                          
mysql  Ver 15.1 Distrib 10.3.22-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

Content of `mysql_version.h` used for `libmysqlclient`
```
#define PROTOCOL_VERSION            10
#define MYSQL_SERVER_VERSION       "8.0.20"
#define MYSQL_BASE_VERSION         "mysqld-8.0"
#define MYSQL_SERVER_SUFFIX_DEF    "-0ubuntu0.20.04.1"
#define MYSQL_VERSION_ID            80020
#define MYSQL_PORT                  3306
#define MYSQL_ADMIN_PORT            33062
#define MYSQL_PORT_DEFAULT          0
#define MYSQL_UNIX_ADDR            "/var/run/mysqld/mysqld.sock"
#define MYSQL_CONFIG_NAME          "my"
#define MYSQL_PERSIST_CONFIG_NAME  "mysqld-auto"
#define MYSQL_COMPILATION_COMMENT  "(Ubuntu)"
#define MYSQL_COMPILATION_COMMENT_SERVER  "(Ubuntu)"
#define LIBMYSQL_VERSION           "8.0.20"
#define LIBMYSQL_VERSION_ID         80020
```

**Comment by p-alik** [comment]
Like in your case `check_set_bind` and `check_enum_bind` tests failed agianst `mysqld  Ver 10.2.17-MariaDB for Linux on x86_64 (MariaDB Server)`. `check_all_the_types` passed without any changes.

```
test mysql::connection::bind::tests::check_enum_bind ... FAILED
test mysql::connection::bind::tests::check_set_bind ... FAILED
test mysql::connection::bind::tests::check_all_the_types ... ok
test mysql::connection::bind::tests::check_json_bind ... ok
```


* `include/mysql/mysql_version.h`
```  
/* Do not edit this file directly, it was auto-generated by cmake */

#warning This file should not be included by clients, include only <mysql.h>

#include <mariadb_version.h>
#define LIBMYSQL_VERSION MARIADB_CLIENT_VERSION_STR
```

* `include/mysql/mariadb_version.h`
```
/* Copyright Abandoned 1996, 1999, 2001 MySQL AB
   This file is public domain and comes with NO WARRANTY of any kind */

/* Version numbers for protocol & mysqld */

#ifndef _mariadb_version_h_
#define _mariadb_version_h_

#ifdef _CUSTOMCONFIG_
#include <custom_conf.h>
#else
#define PROTOCOL_VERSION                10
#define MARIADB_CLIENT_VERSION_STR      "10.2.17"
#define MARIADB_BASE_VERSION            "mariadb-10.2"
#define MARIADB_VERSION_ID              100217
#define MYSQL_VERSION_ID                100217
#define MARIADB_PORT                    3306
#define MARIADB_UNIX_ADDR               "/run/mysqld/mysqld.sock"
#define MYSQL_CONFIG_NAME               "my"

#define MARIADB_PACKAGE_VERSION "3.0.4"
#define MARIADB_PACKAGE_VERSION_ID 30004
#define MARIADB_SYSTEM_TYPE "Linux"
#define MARIADB_MACHINE_TYPE "x86_64"
#define MARIADB_PLUGINDIR "/nix/store/n9kl72m8b4f101p8y0zkq8smzawqx2sa-mariadb-10.2.17/lib/mysql/plugin"

/* mysqld compile time options */
#ifndef MYSQL_CHARSET
#define MYSQL_CHARSET                   ""
#endif
#endif

/* Source information */
#define CC_SOURCE_REVISION ""

#endif /* _mariadb_version_h_ */
```

**edit** I'd to edit `Cargo.toml` to run tests in `nix-shell`-environment
```
diff --git a/diesel/Cargo.toml b/diesel/Cargo.toml
index 1eab9b51..ee201150 100644
--- a/diesel/Cargo.toml
+++ b/diesel/Cargo.toml
@@ -53,7 +53,7 @@ huge-tables = ["64-column-tables"]
 128-column-tables = ["64-column-tables"]
 postgres = ["pq-sys", "bitflags", "diesel_derives/postgres"]
 sqlite = ["libsqlite3-sys", "diesel_derives/sqlite"]
-mysql = ["mysqlclient-sys", "url", "percent-encoding", "diesel_derives/mysql", "bitflags"]
+mysql = ["mysqlclient-sys", "url", "percent-encoding", "diesel_derives/mysql", "bitflags", "bigdecimal", "chrono"]
 with-deprecated = []
 deprecated-time = ["time"]
 network-address = ["ipnetwork", "libc"]
```

**Comment by weiznich** [comment]
I've pushed a new version with some fixes. Hopefully now the tests should pass on all resent platforms. Any help testing that is appreciated.

**Comment by p-alik** [comment]
* `10.2.17-MariaDB` OK
* ` 10.3.15-MariaDB` `check_all_the_types` failed like in in [previous attempt](#issuecomment-626946153)

**Comment by weiznich** [comment]
Ok I've run some more tests and the situation is quite complex…
(Who the hell did design this mess…)
Mysql:
* 5.6 - 5.7: Json is not supported as column type (therefore all json related tests fail), everything else seems to "work" with the existing test cases
* 8.0: Json is supported as column type, returns `MYSQL_TYPE_JSON` as default case if no explicit bind type is set. Multipoint came back as `MULTIPOINT((0 0),(10 10),(10 20),(20 20))`

Mariadb:
* 10.0 and 10.1 Json is not supported as column type (therefore failing json tests), everything else seems to "work" with the existing test cases
* 10.2 Json is supported as column type, returns `MYSQL_TYPE_BLOB` as default case if no explicit bind type is set, requesting it as `MYSQL_TYPE_JSON` also works fine, all other tests work
* 10.3 and 10.4 behave as mysql 8.0
* 10.5 behaves like mariadb 10.2

The newly pushed version should fix the behavior on all versions I've tested. Any help validating this on another system would be appreciated.

**Comment by p-alik** [comment]
All tests could be successfully executed against both [aforementioned](5#issuecomment-629597343) MariaDB's

**Pull request closed without merging**
